controllers/ParentChildController.php
<?php

namespace app\controllers;

use Yii;
use app\models\ParentChild;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\classes\SessionHandler;

/**
 * ParentChildController implements the CRUD actions for ParentChild model.
 */
class ParentChildController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ParentChild models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => ParentChild::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ParentChild model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ParentChild model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {   
        $model = ParentChild::findOne(['motherId' => $id]);
        return $this->renderAjax('create',['model' => (isset($model['id']))?$model:new ParentChild(),'motherId' => $id]);
    }
     public function actionAjax()
    {
    	$model = new ParentChild();
    	$postForm = $_POST['ParentChild'];
    	$returnCreateValue = 'ParentChild Created';
    	$returnUpdateValue = 'ParentChild Updated';
    	$returnFalseValue = 'ParentChild Not Inserted';
    	$respondentId = Yii::$app->cache->get('motherId');;
    	if(isset($postForm))
    	{
    		$findModel = ParentChild::findOne(['motherId' => $respondentId]);
    		if(isset($findModel['id']))
    		{
    			$model = $this->findModel($findModel['id']);
    			$returnValue = $returnUpdateValue;
    			$model->attributes = $postForm;
    		}
    		else
    		{
    			$returnValue = $returnCreateValue;
    			$model->attributes = $postForm;
    			//$model->created_dtm = date('Y-m-d H:i:s');
    		}
    		$model->motherId = $respondentId;
    		$model->save();
    	}
    	return $returnValue;
    }
    /**
     * Updates an existing ParentChild model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ParentChild model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ParentChild model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ParentChild the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ParentChild::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/parent-child/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ParentChild */
/* @var $form yii\widgets\ActiveForm */
Yii::$app->cache->set('motherId',$motherId);
?>

<div class="parent-child-form">

    <?php $form = ActiveForm::begin(['id' => 'formParentChild']); ?>
    <div id="withBoxShadow" class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
	    <div class="row">
		    <div class="col-lg-4 col-md-4">
			    <?= $form->field($model, 'child_name')->textInput(['maxlength' => true]) ?>
		    </div>
		    <!-- add last date visit -->
	    </div>
	    <div class="row">
		    <div class="col-lg-4 col-md-4">
			    <?= $form->field($model, 'father_name')->textInput(['maxlength' => true]) ?>
		    </div>
		    <!--father id and last date of visit-->
	    </div>
	    <div class="row">
		    <div class="col-lg-4 col-md-4">
			    <?= $form->field($model, 'care_taker')->textInput(['maxlength' => true]) ?>
		    </div>
		    <!--add caretaker id last visit date-->
	    </div>	
    </div>	

    <?php ActiveForm::end(); ?>

</div>
<?php
     $this->registerJs('
	$("#formParentChild").change(function(){
		autoSave({url : "parent-child/ajax",formName : "formParentChild"});	
	});		
')
?>

views/parent-child/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\ParentChild */

/*$this->title = 'Create Parent Child';
$this->params['breadcrumbs'][] = ['label' => 'Parent Children', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;*/
?>
<div class="parent-child-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <?= $this->render('_form',['model' => $model,'motherId' => $motherId]) ?>

</div>

views/parent-child/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Parent Children';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="parent-child-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Parent Child', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'motherId',
            'childId',
            'child_name',
            'father_name',
            // 'care_taker',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/parent-child/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\ParentChild */

$this->title = 'Update Parent Child: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Parent Children', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="parent-child-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/parent-child/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\ParentChild */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Parent Children', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="parent-child-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'motherId',
            'childId',
            'child_name',
            'father_name',
            'care_taker',
        ],
    ]) ?>

</div>