models/PtsdChecklist.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "ptsd_checklist".
 *
 * @property integer $id
 * @property integer $mother_id
 * @property string $created_dtm
 * @property string $last_updated_dtm
 * @property string $updated_by
 * @property integer $intrusive_recollect
 * @property integer $flashbacks
 * @property integer $upset_remainders
 * @property integer $distressing_dreams
 * @property integer $physical_remainders
 * @property integer $avoid_thoughts
 * @property integer $avoid_remainders
 * @property integer $psychogenic_amnesia
 * @property integer $anhedonia
 * @property integer $estrangement_others
 * @property integer $psychic_numbing
 * @property integer $foreshortened_future
 * @property integer $sleep_difficulty
 * @property integer $irritability
 * @property integer $concentrattion_impaired
 * @property integer $hyper_vigilant
 * @property integer $exaggerated_startle
 * @property integer $score
 */
class PtsdChecklist extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ptsd_checklist';
    }
	
	private static $_db;
    
    public static function getDb() {
        if (isset(self::$_db)) {
            return self::$_db;
        }
        return \yii\db\ActiveRecord::getDb();
    }
    
    public static function setDb($db) {
        self::$_db = $db;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mother_id','assessment_id','scale_id', 'intrusive_recollect', 'flashbacks', 'upset_remainders', 'distressing_dreams', 'physical_remainders', 'avoid_thoughts', 'avoid_remainders', 'psychogenic_amnesia', 'anhedonia', 'estrangement_others', 'psychic_numbing', 'foreshortened_future', 'sleep_difficulty', 'irritability', 'concentrattion_impaired', 'hyper_vigilant', 'exaggerated_startle', 'score'], 'integer'],
            [['created_dtm', 'last_updated_dtm'], 'safe'],
            [['updated_by'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mother_id' => 'Patient ID',
            'created_dtm' => 'Created Date',
            'last_updated_dtm' => 'Last Updated Date',
            'updated_by' => 'Updated By',
            'intrusive_recollect' => 'Intrusive Recollect',
            'flashbacks' => 'Flashbacks',
            'upset_remainders' => 'Upset Remainders',
            'distressing_dreams' => 'Distressing Dreams',
            'physical_remainders' => 'Physical Remainders',
            'avoid_thoughts' => 'Avoid Thoughts',
            'avoid_remainders' => 'Avoid Remainders',
            'psychogenic_amnesia' => 'Psychogenic Amnesia',
            'anhedonia' => 'Anhedonia',
            'estrangement_others' => 'Estrangement Others',
            'psychic_numbing' => 'Psychic Numbing',
            'foreshortened_future' => 'Foreshortened Future',
            'sleep_difficulty' => 'Sleep Difficulty',
            'irritability' => 'Irritability',
            'concentrattion_impaired' => 'Concentrattion Impaired',
            'hyper_vigilant' => 'Hyper Vigilant',
            'exaggerated_startle' => 'Exaggerated Startle',
            'score' => 'Score',
        ];
    }

      public function beforeSave($insert)
    {
        return true;
    }



public function afterFind() {
    return true; //don't forget this
}
}

controllers/PtsdChecklistController.php
<?php

namespace app\controllers;

use Yii;
use app\models\PtsdChecklist;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\classes\SessionHandler;
use app\models\Users;
use app\classes\RespondentType;

/**
 * PtsdChecklistController implements the CRUD actions for PtsdChecklist model.
 */
class PtsdChecklistController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all PtsdChecklist models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => PtsdChecklist::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single PtsdChecklist model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new PtsdChecklist model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $motherId = Yii::$app->session->get('motherId');
        $assessmentId = Yii::$app->session->get('assessmentId');
		//$respondentId = Yii::$app->session->get('respondentId');
        $resp = new RespondentType();
        $respondentId =$resp->getTypeId('m');
        $check = PtsdChecklist::findOne(['mother_id' => $motherId,'assessment_id' => $assessmentId,'respondent_id'=>$respondentId]);
    	if(isset($check['id']))
    	{
    		$model = $this->findModel($check['id']);
    	}
    	else
    	{
    		$model = new PtsdChecklist();
    	}
    	return $this->render('create', ['model' => $model]);
    }
	
	public function actionAjax()
    {
    	$model = new PtsdChecklist();
    	$postForm = $_POST['PtsdChecklist'];
    	$returnCreateValue = 'PtsdChecklist Created';
    	$returnUpdateValue = 'PtsdChecklist Updated';
    	$returnFalseValue = 'PtsdChecklist Not Inserted';
    	$motherId = Yii::$app->session->get('motherId');
		$assessmentId = Yii::$app->session->get('assessmentId');
        //$respondentId = Yii::$app->session->get('respondentId');
        $resp = new RespondentType();
        $respondentId =$resp->getTypeId('m');
    	if(isset($postForm))
    	{
    		$findModel = PtsdChecklist::findOne(['mother_id' => $motherId,'assessment_id' => $assessmentId,'respondent_id'=>$respondentId]);
    		if(isset($findModel['id']))
    		{
    			$model = $this->findModel($findModel['id']);
    			$returnValue = $returnUpdateValue;
    			$model->attributes = $postForm;
                
    		}
    		else
    		{
    			$returnValue = $returnCreateValue;
    			$model->attributes = $postForm;
                $model->scale_id=9;
				$model->created_dtm= date('Y:m:d h:i:s');
                
    		}
    		$model->mother_id = $motherId;
            $model->assessment_id= $assessmentId;
			$model->respondent_id= $respondentId;
			$model->last_updated_dtm= date('Y:m:d h:i:s');
            $model->updated_by=Users::findOne(['id' => Yii::$app->user->id])->username;
    		$model->save();
            $scale = new \app\models\Scores;
            $scale->updateScales($motherId,$assessmentId,$model->scale_id,$model->score);
            
    			
    	}
    	return $returnValue;
    }

    /**
     * Updates an existing PtsdChecklist model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing PtsdChecklist model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the PtsdChecklist model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return PtsdChecklist the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = PtsdChecklist::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/ptsd-checklist/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
$keyPair = [-15 => '-15: Child Not Co-Operative For Assessment',
		  -14 => '-14: Not Available For Assessment',
		  -11 => '-11: Inadequate Information',
		  -10 => '-10: Not Applicable',
		  -9 => '-9: Missing',
		  -8 => '-8: Refused',
		  -7 => '-7: Partner Accompanied Missing',
		  -6 => '-6: Family Accompanied Missing',
		  -5 => '-5: Missing:Not Asked',
		  -3 => '-3: No Such Relationship/No Partner'];
/* @var $this yii\web\View */
/* @var $model app\models\PtsdChecklist */
/* @var $form yii\widgets\ActiveForm */
$this->registerJsFile('@web/js/scales.js',['depends' => [\yii\web\JqueryAsset::className()]]);
?>

<div class="ptsd-checklist-form">

    <?php $form = ActiveForm::begin(['id' => 'formPtsdchecklist']); ?>

    <div id="withBoxShadow">
	
	
	<caption><b>ಕಳೆದ ಭೇಟಿಯಿಂದ  ಅಥವಾ ಕಳೆದ  ತಿಂಗಳಿನಿಂದ  ಈ ಕೆಳಗಿನವುಗಳಲ್ಲಿ  ಯಾವುದಾದರನ್ನೂ ಅನುಭವಿಸಿದ್ದೀರಾ ?</b></caption>
	<table border="1" class="responsive-scales">
		<thead>
                <tr>
				    <th></th>
                    <th>ಇಲ್ಲವೇ ಇಲ್ಲ </th>
                    <th>ಸ್ವಲ್ಪ ಮಟ್ಟಿಗೆ </th>
                    <th>ಸಾಧಾರಣವಾಗಿ </th>
                    <th>ಗಮನಾರ್ಹವಾಗಿ </th>
                    <th>ಅತ್ಯಂತ ಅತಿರೇಕ </th>
					<th>Other Answers</th>
                </tr> 
        </thead>
	<tbody>	
		<tr>
		<td>1) ಪದೇ ಪದೇ ಆಘಾತದ ನೆನಪುಗಳು ಮರುಕಳಿಸುವುದರಿಂದ</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'intrusive_recollect')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'intrusive_recollect')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>2)   ಆಘಾತದ / ಮರೆಯಲಾಗದಂತಹ ಮರುಕಳಿಸುವ ನೆನಪುಗಳು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'flashbacks')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'flashbacks')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>3) ನೆನಪುಗಳಿಂದ ಬೇಜಾರು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'upset_remainders')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'upset_remainders')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>4) ಕಳವಳಗೊಳ್ಳುವ ಕನಸುಗಳು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'distressing_dreams')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'distressing_dreams')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>5) ನೆನಪುಗಳಿಗೆ ದೈಹಿಕ ಪ್ರತಿಕ್ರಿಯೆಗಳು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'physical_remainders')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'physical_remainders')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>6) ಯೋಚನೆಗಳಿಂದ ದೂರವಿರುವುದು/ತಪ್ಪಿಸಿಕೊಳ್ಳುವುದು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'avoid_thoughts')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'avoid_thoughts')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>7) ಜ್ಞಾಪಕ/ನೆನಪುಗಳಿಂದ ತಪ್ಪಿಸಿಕೊಳ್ಳುವುದು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'avoid_remainders')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'avoid_remainders')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>8) ಮಾನಸಿಕ ಮೂಲಗಳಿಂದ ಮರೆವು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'psychogenic_amnesia')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'psychogenic_amnesia')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>9) ಆನಂದ ನೀಡುತ್ತಿದ್ದಂತಹ  ಚಟುವಟಿಕೆಗಳು, ಈಗ ಸಂತೋಷ  ನೀಡುತ್ತಿಲ್ಲ </td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'anhedonia')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'anhedonia')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>10) ಇತರರಿಂದ ಆಗಲಿಕೆ </td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'estrangement_others')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'estrangement_others')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>11) ಮಾನಸಿಕವಾಗಿ ಸ್ತಬ್ಧಗೊಳ್ಳುವುದು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'psychic_numbing')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'psychic_numbing')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>12) ಭವಿಷ್ಯದಲ್ಲಿ ನಡೆಯಬಹುದಾದಂತಹ ಘಟನೆ, ಈಗಲೇ ನಡೆಯಬಹುದೆ೦ಬ ಅನಿಸಿಕೆ </td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'foreshortened_future')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'foreshortened_future')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>13) ನಿದ್ರೆಯ ತೊಂದರೆ </td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'sleep_difficulty')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'sleep_difficulty')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>14) ಕಿರಿ ಕಿರಿ / ಕೋಪ</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'irritability')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'irritability')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>15) ದುರ್ಬಲಗೊಂಡ  ಏಕಾಗ್ರತೆ</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'concentrattion_impaired')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'concentrattion_impaired')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>16) ಅತಿ ಜಾಗರೂಕ /ಎಚ್ಚರವಾಗಿರುವುದು </td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'hyper_vigilant')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'hyper_vigilant')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td>17) ಅತಿಯಾಗಿ  ಚಕಿತ /ಆಶ್ಚರ್ಯಗೊಳ್ಳುವುದು</td>
		<?php for($i = 1;$i < 6;$i++):?>
		<td><?= $form->field($model, 'exaggerated_startle')->radio(['label' => $i, 'value' => $i])?>
				</td>
		<?php endfor;?>
		<td>
			<?= $form->field($model, 'exaggerated_startle')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?>
		</td>
		</tr>
		
		<tr>
		<td id="scaleflag" colspan="7" class="hidden"><?= $form->field($model, 'score')->input('number',['readonly'=>true])->label(false);?></td>
		</tr>
    </tbody>
	</table>
	
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php $this->registerJs('
	$("#"+formObj.formName).one("change",function()
	{
		autoSaveObj = formObj;
	});
',\yii\web\View::POS_READY)?>

<script type="text/javascript">
	formObj = {url:"ptsd-checklist/ajax",formName : "formPtsdchecklist"};
    var calc = function () {
        var totalValue = 0;
		var root = 'ptsdchecklist';
        var id = '#'+root+'-';
		var clas = '.field-'+root+'-';
        var arr = ['intrusive_recollect','flashbacks','upset_remainders','distressing_dreams','physical_remainders', 'avoid_thoughts', 'avoid_remainders', 'psychogenic_amnesia', 'anhedonia', 'estrangement_others', 'psychic_numbing', 'foreshortened_future', 'sleep_difficulty', 'irritability', 'concentrattion_impaired', 'hyper_vigilant', 'exaggerated_startle'];

        for (var i in arr) {
            var val = $(clas + arr[i] + ' input[type=radio]:checked').val();
			if (parseInt(val)>=0) {
                totalValue += parseInt(val);
            }
        }
		
        $(id+'score').val(totalValue);
		autoSaveObj = formObj;
    }
</script>

views/ptsd-checklist/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\PtsdChecklist */

$this->title = 'Ptsd Checklist';
$this->params['breadcrumbs'][] = ['label' => 'Ptsd Checklists', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ptsd-checklist-create">

    <h1 align="center">ಪಿ ಟಿ ಎಸ್ ಡಿ ಪರೀಕ್ಷಾ ಪಟ್ಟಿ </h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>