models/Breastfeeding.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "breastfeeding".
 *
 * @property integer $id
 * @property integer $mother_id
 * @property integer $assessment_id
 * @property string $created_dtm
 * @property string $last_updated_dtm
 * @property string $updated_by
 * @property integer $determine_enough_milk
 * @property integer $successfully_cope
 * @property integer $without_formula
 * @property integer $lached_properly
 * @property integer $manage_situation
 * @property integer $manage_crying
 * @property integer $wanting_breastfeed
 * @property integer $comfortable_family_members
 * @property integer $satisfied_experience
 * @property integer $deal_time_consuming
 * @property integer $finish_1breast
 * @property integer $continue_feeding
 * @property integer $keepup_baby_demands
 * @property integer $tell_finished
 * @property integer $score
 * @property integer $scale_id
 */
class Breastfeeding extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'breastfeeding';
    }
	
	private static $_db;
    
    public static function getDb() {
        if (isset(self::$_db)) {
            return self::$_db;
        }
        return \yii\db\ActiveRecord::getDb();
    }
    
    public static function setDb($db) {
        self::$_db = $db;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['mother_id', 'assessment_id', 'determine_enough_milk', 'successfully_cope', 'without_formula', 'lached_properly', 'manage_situation', 'manage_crying', 'wanting_breastfeed', 'comfortable_family_members', 'satisfied_experience', 'deal_time_consuming', 'finish_1breast', 'continue_feeding', 'keepup_baby_demands', 'tell_finished', 'score', 'scale_id'], 'integer'],
            [['created_dtm', 'last_updated_dtm'], 'safe'],
            [['updated_by'], 'string', 'max' => 45],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mother_id' => 'Respondent ID',
            'assessment_id' => 'assessment ID',
            'created_dtm' => 'Created Date',
            'last_updated_dtm' => 'Last Updated Date',
            'updated_by' => 'Updated By',
            'determine_enough_milk' => 'Determine Enough Milk',
            'successfully_cope' => 'Successfully Cope',
            'without_formula' => 'Without Formula',
            'lached_properly' => 'Lached Properly',
            'manage_situation' => 'Manage Situation',
            'manage_crying' => 'Manage Crying',
            'wanting_breastfeed' => 'Wanting Breastfeed',
            'comfortable_family_members' => 'Comfortable Family Members',
            'satisfied_experience' => 'Satisfied Experience',
            'deal_time_consuming' => 'Deal Time Consuming',
            'finish_1breast' => 'Finish 1breast',
            'continue_feeding' => 'Continue Feeding',
            'keepup_baby_demands' => 'Keepup Baby Demands',
            'tell_finished' => 'Tell Finished',
            'score' => 'Score',
            'scale_id' => 'Scale ID',
        ];
    }

      public function beforeSave($insert)
    {
        return true;
    }



public function afterFind() {
    return true; //don't forget this
}
}

controllers/BreastfeedingController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Breastfeeding;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use app\classes\SessionHandler;
use app\models\Users;
use app\classes\RespondentType;

/**
 * BreastfeedingController implements the CRUD actions for Breastfeeding model.
 */
class BreastfeedingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Breastfeeding models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Breastfeeding::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Breastfeeding model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
	
	
    /**
     * Creates a new Breastfeeding model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
     public function actionCreate()
    {
       
        $motherId = Yii::$app->session->get('motherId');
        $assessmentId = Yii::$app->session->get('assessmentId');
		//$respondentId = Yii::$app->session->get('respondentId');
         $resp = new RespondentType();
        $respondentId =$resp->getTypeId('m');
		$check = Breastfeeding::findOne(['mother_id' =>  $motherId,'assessment_id' => $assessmentId,'respondent_id'=>$respondentId]);
    	if(isset($check['id']))
    	{
    		$model = $this->findModel($check['id']);
    	}
    	else
    	{
    		$model = new Breastfeeding();
    	}
    	return $this->render('create', ['model' => $model]);
    }
	
	public function actionAjax()
    {
    	$model = new Breastfeeding();
    	$postForm = $_POST['Breastfeeding'];
    	$returnCreateValue = 'Breastfeeding Created';
    	$returnUpdateValue = 'Breastfeeding Updated';
    	$returnFalseValue = 'Breastfeeding Not Inserted';
        $assessmentId = Yii::$app->session->get('assessmentId');
        $motherId = Yii::$app->session->get('motherId');
		//$respondentId = Yii::$app->session->get('respondentId');
         $resp = new RespondentType();
        $respondentId =$resp->getTypeId('m');
    	if(isset($postForm))
    	{
    		$findModel = Breastfeeding::findOne(['mother_id' =>  $motherId,'assessment_id' => $assessmentId,'respondent_id'=>$respondentId]);
    		if(isset($findModel['id']))
    		{
    			$model = $this->findModel($findModel['id']);
    			$returnValue = $returnUpdateValue;
    			$model->attributes = $postForm;
                
    		}
    		else
    		{
    			$returnValue = $returnCreateValue;
    			$model->attributes = $postForm;
                $model->scale_id=14;
                $model->created_dtm= date('Y:m:d h:i:s');
    		}
    		$model->mother_id =  $motherId;
            $model->assessment_id= $assessmentId;
			$model->respondent_id= $respondentId;
			$model->last_updated_dtm= date('Y:m:d h:i:s');
            $model->updated_by=Users::findOne(['id' => Yii::$app->user->id])->username;
    		$model->save();
            $scale = new \app\models\Scores;
            $scale->updateScales( $motherId,$assessmentId,$model->scale_id,$model->score);
            
    			
    	}
    	return $returnValue;
    }


    /**
     * Updates an existing Breastfeeding model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Breastfeeding model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Breastfeeding model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Breastfeeding the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Breastfeeding::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/breastfeeding/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
$keyPair = [-15 => '-15: Child Not Co-Operative For Assessment',
		  -14 => '-14: Not Available For Assessment',
		  -11 => '-11: Inadequate Information',
		  -10 => '-10: Not Applicable',
		  -9 => '-9: Missing',
		  -8 => '-8: Refused',
		  -7 => '-7: Partner Accompanied Missing',
		  -6 => '-6: Family Accompanied Missing',
		  -5 => '-5: Missing:Not Asked',
		  -3 => '-3: No Such Relationship/No Partner'];
/* @var $this yii\web\View */
/* @var $model app\models\Breastfeeding */
/* @var $form yii\widgets\ActiveForm */
$this->registerJsFile('@web/js/scales.js',['depends' => [\yii\web\JqueryAsset::className()]]);
?>

<div   class="breastfeeding-form">

    <?php $form = ActiveForm::begin(['id'=>'formBreastfeeding']); ?>
	<div id="idbfscale">
	<div  id="withBoxShadow" class="col-xs-12 col-md-12 col-lg- col-sm-12">
        <table border="1" class="responsive-scales">
            <thead>
                <tr>
				    <th></th>
                    <th> ವಿಶ್ವಾಸ ಇಲ್ಲವೇ ಇಲ್ಲ </th>
                    <th> ಅಷ್ಟಾಗಿ ವಿಶ್ವಾಸವಿಲ್ಲ </th>
                    <th> ಕೆಲವೊಮ್ಮೆ ವಿಶ್ವಾಸವಿದೆ  </th>
                    <th> ವಿಶ್ವಾಸದಿಂದ್ದಿನಿ</th>
                    <th>ಹೆಚ್ಚು ವಿಶ್ವಾಸದಿಂದ್ದಿನಿ  </th>
                    <th>Other Answers</th>
                </tr> 
            </thead>
            <tbody>
			<tr>
                    <td>1) ನನ್ನ ಮಗುವಿಗೆ ಯಾವಾಗಲೂ ಸಾಕಾಗುವಷ್ಟು ಹಾಲು ಸಿಗುತ್ತಿದೆ ಎಂದು ನಾನು ಖಚಿತಪಡಿಸಬಹುದು.</td>
					<?php for($i = 1;$i < 6;$i++):?>
					<td>
                    <?= $form->field($model, 'determine_enough_milk')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'determine_enough_milk')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

    
			<tr>
                    <td>2) ನನಗಿರುವ ಬೇರೆ ಸವಾಲುಗಳಂತೆಯೇ ನಾನು ಯಾವಾಗಲು ಯಶಸ್ವಿಯಾಗಿ ಎದೆ ಹಾಲು ಕುಡಿಸುವುದನ್ನು ನಿಭಾಯಿಸಬಲ್ಲೆ  </td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'successfully_cope')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
					 <?= $form->field($model, 'successfully_cope')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>
			
			<tr>
                    <td>3) ನಾನು ಬೇರೆ ಯಾವುದೇ ಆಹಾರವನ್ನು ಬಳಸದೇ ನನ್ನ ಮಗುವಿಗೆ ಯಾವಾಗಲೂ ಎದೆ ಹಾಲು ಕುಡಿಸಬಲ್ಲೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'without_formula')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
					 <?= $form->field($model, 'without_formula')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>
			
			<tr >
                    <td>4) ನನ್ನ ಮಗುವಿಗೆ ಪೂರ್ಣವಾಗಿ ಹಾಲುಣಿಸುವಾಗ ನನ್ನ ಮಗುವು ಮೊಲೆಯ ತೊಟ್ಟನ್ನು ಸರಿಯಾದ ರೀತಿಯಲ್ಲಿ  ಹಿಡಿದುಕೊಂಡಿದೆಯೇ  ಎಂದು ಖಚಿತಪಡಿಸಬಲ್ಲೆ </td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'lached_properly')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
					 <?= $form->field($model, 'lached_properly')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>
			<tr >
                    <td>5)ನಾನು ಯಾವಾಗಲೂ ಎದೆ ಹಾಲುಣಿಸುವ ಸಂದರ್ಭವನ್ನು ನನಗೆ ತೃಪ್ತಿಯಾಗುವಂತೆ ನಿಭಾಯಿಸ ಬಲ್ಲೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'manage_situation')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
					 <?= $form->field($model, 'manage_situation')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr >
			
			<tr >
                    <td>6) ನನ್ನ ಮಗುವ್ರ ಆಳುತ್ತಿದ್ದರೂ ಸಹ ನಾನು ಎದೆ ಹಾಲುಣಿಸುವುದನ್ನು ನಿಭಾಯಿಸ ಬಲ್ಲೆ </td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'manage_crying')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'manage_crying')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>7) ನಾನು ನನ್ನ ಮಗುವಿಗೆ ಯಾವಾಗಲೂ ಎದೆ ಹಾಲು ಕುಡಿಸುತ್ತಿರಲು ಇಷ್ಟಪಡುತ್ತೇನೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'wanting_breastfeed')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'wanting_breastfeed')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>8) ನನ್ನ ಕುಟು೦ಬದ ಸದಸ್ಯರು ಇದ್ದಾಗಲೂ ಸಹ ನಾನು ಆರಾಮವಾಗಿ ನನ್ನ ಮಗುವಿಗೆ ಯಾವಾಗಲೂ ಎದೆ ಹಾಲು ಕುಡಿಸಬಲ್ಲೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'comfortable_family_members')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'comfortable_family_members')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>9)ನಾನು ಯಾವಾಗಲೂ ಎದೆ ಹಾಲು ಕುಡಿಸುವ ಅನುಭವದಿಂದ ತೃಪ್ತಿಪಡಬಲ್ಲೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'satisfied_experience')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'satisfied_experience')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>
			
			<tr>
                    <td>10) ಎದೆ ಹಾಲು ಕುಡಿಸುವುದಕ್ಕೆ ಸಾಕಷ್ಟು  ಸಮಯ ಬೇಕೆ೦ಬುದನ್ನು ತಿಳಿದಿದ್ದರೂ, ಅದನ್ನು ಯಾವಾಗಲೂ ನಿರ್ವಹಿಸ ಬಲ್ಲೆ </td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'deal_time_consuming')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
 <?= $form->field($model, 'deal_time_consuming')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>11) ನಾನು ಮಗುವಿಗೆ ಯಾವಾಗಲು ಒಂದು ಮೊಲೆಯ ಹಾಲನ್ನು ಪೂರ್ತಿಯಾಗಿ ಕುಡಿಸಿದ ನಂತರವೇ ಇನ್ನೊಂದು ಮೊಲೆ ಹಾಲು ಕುಡಿಸಬಲ್ಲೆ </td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'finish_1breast')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'finish_1breast')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>12) ಪ್ರತಿ ಬಾರಿಯೂ ನಾನು ಮಗುವಿಗೆ ಹಾಲುಣಿಸುವುದನ್ನು ಮುಂದುವರಿಸಬಲ್ಲೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'continue_feeding')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'continue_feeding')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>13) ಮಗುವಿನ ಎದೆ ಹಾಲು ಕುಡಿಯುವ ಬಯಕೆಯನ್ನು ನಾನು ಯಾವಾಗಲೂ ಸಮರ್ಥವಾಗಿ ನಿಭಾಯಿಸಬಲ್ಲೆ</td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'keepup_baby_demands')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'keepup_baby_demands')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>

			<tr >
                    <td>14)ನನ್ನ ಮಗುವು ಎದೆ ಹಾಲು ಸಂಪೂರ್ಣವಾಗಿ ಕುಡಿದಿದೆ ಎಂದು ನಾನು ಯಾವಾಗಲು ಹೇಳಬಲ್ಲೆ </td>
                    <?php for($i = 1;$i < 6;$i++):?>
					<td><?= $form->field($model, 'tell_finished')->radio(['label' => $i, 'value' => $i])?>
					</td>
					<?php endfor;?>
					<td>
						 <?= $form->field($model, 'tell_finished')->dropDownList($keyPair,['prompt' => 'Select'])->label(false)?> 

					</td>
			</tr>		

			<tr>
                <td></td>
                <td id="scaleflag" colspan="5" class="hidden"><?= $form->field($model, 'score')->input('number',['readonly'=>true])->label(false);?></td>
            </tr>
			
			
			</tbody>
			</table>
	</div>
	</div>
	<?php ActiveForm::end(); ?>
</div>

<?php $this->registerJs('
	$("#"+formObj.formName).one("change",function()
	{
		autoSaveObj = formObj;
	});
',\yii\web\View::POS_READY)?>

<script type="text/javascript">
	formObj = {'url': "breastfeeding/ajax",'formName' : "formBreastfeeding"};
     var calc = function () {
        var totalValue = 0;
		var root = 'breastfeeding';
        var id = '#'+root+'-';
		var clas = '.field-'+root+'-';
        var arr = ['determine_enough_milk','successfully_cope','without_formula','lached_properly','manage_situation',
		'manage_crying','wanting_breastfeed','comfortable_family_members','satisfied_experience','deal_time_consuming',
		'finish_1breast','continue_feeding','keepup_baby_demands','tell_finished'];
		
		for (var i in arr) {
            var val = $(clas + arr[i] + ' input[type=radio]:checked').val();
			if (parseInt(val)>=0) {
                totalValue += parseInt(val);
            }
        }
		
        $(id+'score').val(totalValue);
		autoSaveObj = formObj;
    }
</script>

views/breastfeeding/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Breastfeeding */

$this->title = 'Create Breastfeeding';
$this->params['breadcrumbs'][] = ['label' => 'Breastfeedings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="breastfeeding-create">

    <h1 align="center">ಎದೆ ಹಾಲುಣಿಸುವ ಸ್ವಸಾಮರ್ಥ್ಯದ ಪ್ರಶ್ನಾವಳಿ </h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>