controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use yii\helpers\Json;
use app\classes\SessionHandler;
use app\models\Mother;
use app\classes\ReportProcessor;
use app\classes\SyncOperations;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
   /* public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }*/
    public function behaviors()
    {
	return [
        	'ghost-access'=> [
            	'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
        	],
	    ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
    
    /**
     * Displays homepage.
     *
     * @return string
     */
  
     public function actionIndex()
    {
        $session = new SessionHandler();
    	$session->clearSessions();
        return $this->render('index',[
    								'dataProvider' => new ActiveDataProvider([
    													'query' => Mother::find()
    												])
    							]);
    }
    
    public function actionSync(){
        $session = new SessionHandler();
        $session->clearSessions();
        return $this->render('sync');
    }
    
    public function actionSyncprocess(){
        $sync = new SyncOperations();
        return $sync->process();
    }

    
    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }
	
	public function actionExport(){
	    $session = new SessionHandler();
	    $session->clearSessions();
    	return $this->render('export');
    }
	
	public function actionReportgenerator($assesstype){
    	$report = new ReportProcessor();
    	$data = $report->getReport($assesstype);
		$dt = date('Y:m:d h:i:s');
    	$file = "$dt.bchads.csv";
    	header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    	header('Content-Disposition: attachment; filename='.$file);
    	$print = null;
    	for($i = 0;$i < count($data);$i++)
    	{
    		$values = implode(array_values($data[$i]),",");
    		if($i == 0)
    		{
    			$keys = implode(array_keys($data[$i]),",");
    			$print .= $keys."\n";
    		}
    		$print .= $values."\n";
    	}
		
    	echo $print;    
    }
	
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
    	$session = new SessionHandler();
    	$session->clearSessions();
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    public function actionAdmin()
    {
        $session = new SessionHandler();
        $session->clearSessions();
        return $this->render('admin');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/admin.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="col-md-6 col-md-offset-4 col-lg-6 col-lg-offset-4">
	<div class="row">
		<div class="col-sm-6 col-md-3 col-lg-3 form-group">
			<?php echo Html::tag('div',Html::a('Users',Url::to(['/user-management/user/index']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=user-management/user/index'"])?>
		  </div>
		 <div class="col-sm-6 col-md-3 col-lg-3 form-group">
		 	<?php echo Html::tag('div',Html::a('Roles',Url::to(['/user-management/role/index']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=user-management/role/index'"])?>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12 col-md-6 col-lg-6 form-group">
			<?php echo Html::tag('div',Html::a('Change own password',Url::to(['/user-management/auth/change-own-password']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=user-management/auth/change-own-password'"])?>
	   	</div>
	</div>
	<div class="row">
		<div class="col-sm-6 col-md-3 col-lg-3 form-group">
			<?php echo Html::tag('div',Html::a('Permission',Url::to(['/user-management/permission/index']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=user-management/permission/index'"])?>
		</div>
		<div class="col-sm-6 col-md-3 col-lg-3 form-group">
			<?php echo Html::tag('div',Html::a('Permission Group',Url::to(['/user-management/auth-item-group/index']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=user-management/auth-item-group/index'"])?>
		</div>
	</div>
    <div class="row">
        <div class="col-sm-6 col-md-3 col-lg-3 form-group">
			<?php echo Html::tag('div',Html::a('Back Up',Url::to(['/backup/index']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=backup/index'"])?>
		</div> 
        <!--<div class="col-sm-6 col-md-3 col-lg-3 form-group">
			< ?php echo Html::tag('div',Html::a('Data Conversion',Url::to(['/dataconversion/index']),['style' => 'text-decoration:none']),["class"=>"admintile tile2","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=dataconversion/index'"])?>
		</div> -->
		<div class="col-sm-6 col-md-3 col-lg-3 form-group">
			<?php echo Html::tag('div',Html::a('Export',Url::to(['/site/export']),['style' => 'text-decoration:none']),["class"=>"admintile","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=site/export'"])?>
		</div>
	</div>
	<div class="row">	
		<div class="col-sm-12 col-md-6 col-lg-6 form-group">
			<?php echo Html::tag('div',Html::a('Synchronization',Url::to(['/site/sync']),['style' => 'text-decoration:none']),["class"=>"admintile","align"=>"center",'onclick'=>"location.href='/bchads/web/index.php?r=site/sync'"])?>
		</div>
    </div>
	
    
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/export.php
<?php
use kartik\daterange\DateRangePicker;
use kartik\date\DatePicker;
use yii\web\View;
$this->registerJsFile('@web/jsControllers/reportController.js',['depends' => [\app\assets\AppAsset::className()]]);
$this->registerCss("
.section {
    height: 100%;
    overflow: auto;
}
.daterangepicker .calendar {
    max-width: 700px;
}
tr{
	height:50px;
}");
?>
<div ng-controller="ReportController">
	<div class="row">
		<!--<div class="col-lg-12 col-md-12">
			<div class="col-lg-4 col-md-4">
			<b>Mother Code:	<input ng-model="mc"></b>
			</div>
			<div class="col-lg-4 col-md-4">
			<b>Assessment Type:	<select ng-model="selectedType" ng-options="x.model for x in assesstypes"></select></b>
			</div>
			<div class = "col-md-1 col-lg-1">
	    	<button type = "button" class = "btn btn-success btn-sm" ng-click = "getIndReportGenerator()">Export</button>
			</div>
		</div>-->
	</div><br><br>
	
	
	<div class = "row">
	<div class = "col-lg-12 col-md-12">
		<!--<div class = "col-md-6 col-lg-6">
		< ?php 	
	      				echo '<div class="drp-container">';
	      				echo DateRangePicker::widget([
    							'name'=>'date_range_1',
	      						'value'=>date('d-M-Y').' to '.date('d-M-Y'),
								'convertFormat'=>true,
	      						'useWithAddon'=>true,
    							'presetDropdown'=>true,
    							'hideInput'=>true,
								'pluginOptions'=>
									[
										'locale'=>[
											'format'=>'d-M-Y',
											'separator'=>' to ',
										],
										'opens'=>'right'
									],
	      						'options' => 
	      							[
	      								'id' => 'daterangeforline'
	      							]
						]);		
	      				echo '</div>';
		?>
	    </div>-->
			<div class="col-lg-4 col-md-4 export">
			<b>Assessment Type:	<select ng-model="selectedType" ng-options="x for x in assesstypes"></select></b>
			</div>
	    <div class = "col-md-1 col-lg-1">
	    	<button type = "button" class = "btn btn-success" ng-click = "getReportGenerator()">Export</button>
	    </div>
	</div>	
	</div><br>
	
	
		
	
</div>
<style>
.export select{
	width:200px;
	height:35px;
}
</style>

views/site/index.php
<?php
use yii\data\ActiveDataProvider;
use yii\helpers\Url;
use yii\helpers\Html;

?>
<div class="site-index">
	
	<div>
		<?php 
				echo $this->render('/mother/index', [
						'dataProvider' => $dataProvider
    				]); 
		?>
	</div>
	
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/sync.php
<button type = "button" class = "btn btn-success" ng-click = "startSynchronization()" ng-disabled = "sync.progress">Synchronize</button>
<div class="progress" ng-show = "sync.progress">
	<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%">
    	Synchronizing.Please Wait...
	</div>
</div>
<div ng-show = "sync.message">
	<h3>{{sync.message}}</h3>
</div>